version: '3'
services:
  web:
    build: .
    ports:
      - "5000:8080"
  db:
    image: "mysql"
    environment:
     MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    volumes:
      - db-data:/foo

volumes:
  db-data: